#!/usr/bin/python3
def raise_exception():
    x = 5
    y = 'ALX'
    sum_variable = x + y
    return (sum_variable)
